### ISSUE TITLE
Render a real page, reload, or redirect when no cookie exists

### ISSUE THREAD

**Issue by pld** [onaio/kpi#3]
Discussion:

@pld
When does the user see a raw URL like this? Or does this never get to the user? If so we'll want to show them something prettier, or just redirect them.

@ivermac
They should get the page when they refresh the formbuilder page. The other thing I had thought but I hadn't implemented was to check if the authentication cookie exists before deploying (when a user clicks the save button) to onadata i.e if the auth cookie is not available, js would refresh page.

@pld
OK, since this is public we need to do something more user friendly than render text here

https://github.com/onaio/kpi/pull/1#discussion-diff-91774375R111

**Comment by ivermac** [comment]
I have tried the idea of redirecting but zebra ended up truncating part of the url i.e.
url sent to zebra for redirecting - `http://localhost:8080/#/forms/aT9HCzSbnzg2qtnJcnD7Yj/edit`
url redirected to by zebra after authentication - `http://localhost:8080`. 
My suggestion would be to render a real page that asks a user to authenticate in a different tab then refresh the real page. We can help from @rowo. @pld thoughts?

**Comment by pld** [comment]
Why is it truncating? Let's fix that

**Comment by ivermac** [comment]
I don't know why that's being truncated. Not sure if it's a straight forward fix. If we can have someone in zebra check it out that would be great

**Comment by pld** [comment]
zebra issue related to this, https://github.com/onaio/zebra/issues/4881

**Comment by pld** [comment]
OK, as detailed here, most browsers ignore URL fragments (the hash... part), https://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects, so that's a shame. There's nothing zebra can do about this, but I added some more detailed tests to confirm it's redirect locations are correctly including the fragment.

**Comment by pld** [comment]
@ivermac I think we should do your opening a new tab idea. @rowo thoughts?

**Comment by pld** [comment]
Thinking about what's happening, this could be a problem on the formbuilder/node side not reading the fragment correctly in a 302, @ivermac have you seen the HTTP requests directly? Do they include the fragment?

**Comment by rowo** [comment]
<img width="959" alt="screen shot 2017-01-03 at 11 50 55 am" src="https://cloud.githubusercontent.com/assets/1584163/21615340/16be4378-d1ab-11e6-86c0-7b0614fc6929.png">

**Comment by ivermac** [comment]
@pld I don't think it's a formbuilder issue. I used the following the code to test the redirect on the client side
```javascript
if (document.cookie.indexOf("__enketo") < 0) {
      var current_url = window.location.href;
      window.location = "http://localhost:3005/login?return_url=" + current_url;
    }
```
And it redirected correctly to zebra - the url fragment was present at the time the zebra's login page loaded.

**Comment by pld** [comment]
OK, we're being silly, the return URL needs to be URL encoded, otherwise the redirector can't tell that the hash belongs to the redirect and not the current URL. d'oh!

**Comment by pld** [comment]
Hah, so with `http://localhost:3000/login?return_url=https://forms.ona.io/%23/forms/au6zbTAZ5sU3sMr8E5vVTm/edit` it just works!
