### ISSUE TITLE
Remove link to Kobotoolbox site under the Form Layout option

### ISSUE THREAD

**Issue by bmalina** [onaio/kpi#8]
When selecting the form layout, the read more link directs one to kobotoolbox site. See screenshot.

![image](https://cloud.githubusercontent.com/assets/20789710/21683442/6b4e8cc0-d36a-11e6-8779-d2f5e8ab5e39.png)

Option should be removed.

**Comment by skambo** [comment]
@bmalina I think the links will point to Ona help when this issue is closed? https://github.com/onaio/help/issues/242

**Comment by msschroeder** [comment]
@skambo you are correct they will point to the additional documentation based on onaio/help#242 but the link is still being determined as is not on helpsite yet.

**Comment by msschroeder** [comment]
Additionally, there is another link (question mark in the circle) in the cascading filter that will need to be updated.

<img width="476" alt="screen_shot_2017-01-09_at_5_19_48_pm" src="https://cloud.githubusercontent.com/assets/20777928/21769531/3535ea24-d690-11e6-8360-74523ad57441.png">
