### ISSUE TITLE
have home page redirect to ona.io

### ISSUE THREAD

**Issue by pld** [onaio/kpi#9]
redirect forms.ona.io to ona.io

**Comment by ivermac** [comment]
So implementing this is not straight forward. There are routes that are defined on the client side using [react-router](https://github.com/ReactTraining/react-router) and the landing page is one of them. From the [redirecting docs](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#redirect) I cannot find a way to redirect to a full path url. I tried the following code after commenting [this line](https://github.com/onaio/kpi/blob/onaio/jsapp/js/app.es6#L1586):
```javascript
<Redirect from="download" to="http://localhost:3005" />
```
But I got the following error message:
<img width="830" alt="screen shot 2017-01-10 at 17 02 44" src="https://cloud.githubusercontent.com/assets/1128227/21808938/91bb851c-d756-11e6-88a5-988ae44b7c76.png">
I defined a zebra home route and updated my redirect component
```javascript
<Route name="zebra-home" path="http://localhost:3005" />
...
<Redirect from="download" to="zebra-home" />
```
But the home page rendered with a url that I didn't expect
![image](https://cloud.githubusercontent.com/assets/1128227/21809207/b92e376a-d757-11e6-8784-473a5e4d03ff.png)

We'll need to think of another way unless the E-SIR devs know a workaround to this

**Comment by pld** [comment]
Where in the code are you making this change?

**Comment by ivermac** [comment]
As mentioned above, I commented [this line](https://github.com/onaio/kpi/blob/onaio/jsapp/js/app.es6#L1586) and replaced with the following:
```javascript
<Redirect from="download" to="http://localhost:3005" />
```
and later
```javascript
<Route name="zebra-home" path="http://localhost:3005" />
...
<Redirect from="download" to="zebra-home" />
```
Once the view of the home url - [this one](https://github.com/onaio/kpi/blob/onaio/kpi/urls.py#L54) - has been loaded to the client side, the client side routing ([this section](https://github.com/onaio/kpi/blob/onaio/jsapp/js/app.es6#L1571-L1631)) takes over.

**Comment by pld** [comment]
This internet implies you can't do this via routes, which makes sense. We'll need to set `window.location` to do this

**Comment by ivermac** [comment]
Where would this change be?

**Comment by pld** [comment]
I don't the app well, you'll have to figure that out, maybe look if there's a place before what is causing the error is called to insert that, or if there's something that's always called on loading the homepage.

Another way would be to wrap a try/catch around some JS that's throwing the error you see when loading the homepage and do the redirect there.
